packages:
  - 'packages/*'

catalog:
  '@types/markdown-it': ^14.1.2
  'markdown-it': ^14.1.0
  'npm-run-all2': ^6.2.0
  'vite': ^5.3.1
  'typescript': ~5.4.0
  'less': ^4.2.0
  '@vitejs/plugin-vue-jsx': '^4.0.0'
  'vue': '^3.4.29'
