name: Release

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm -r --no-git-checks publish
