name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release

      - name: Checkout
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: actions/checkout@v4

      - name: Install pnpm
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: corepack enable

      - name: Install Node.js
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: pnpm i

      - name: Build
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: pnpm build

      - name: Publish
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
